-- Script para crear tablas en Oracle XE 18 usando el esquema SYSTEM
-- NO usar ALTER SESSION SET CONTAINER, las tablas se crean en TESTDB automáticamente

-- 1. Crear tabla de departamentos
CREATE TABLE SYSTEM.DEPARTAMENTOS (
    DEPARTAMENTO_ID NUMBER(10) PRIMARY KEY,
    NOMBRE_DEPARTAMENTO VARCHAR2(100) NOT NULL,
    UBICACION VARCHAR2(200),
    PRESUPUESTO NUMBER(12,2),
    FECHA_CREACION DATE DEFAULT SYSDATE
);

-- 2. Crear tabla de empleados
CREATE TABLE SYSTEM.EMPLEADOS (
    EMPLEADO_ID NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    FECHA_CONTRATACION DATE DEFAULT SYSDATE,
    SALARIO NUMBER(10,2) CHECK (SALARIO > 0),
    DEPARTAMENTO_ID NUMBER(10),
    ACTIVO CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S', 'N'))
);

-- 3. Agregar foreign key
ALTER TABLE SYSTEM.EMPLEADOS 
ADD CONSTRAINT FK_EMPLEADO_DEPARTAMENTO 
FOREIGN KEY (DEPARTAMENTO_ID) 
REFERENCES SYSTEM.DEPARTAMENTOS(DEPARTAMENTO_ID);

-- 4. Crear secuencias
CREATE SEQUENCE SYSTEM.SEQ_DEPARTAMENTOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SYSTEM.SEQ_EMPLEADOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 5. Datos de prueba
INSERT INTO SYSTEM.DEPARTAMENTOS (DEPARTAMENTO_ID, NOMBRE_DEPARTAMENTO, UBICACION, PRESUPUESTO)
VALUES (SYSTEM.SEQ_DEPARTAMENTOS.NEXTVAL, 'Tecnología', 'Edificio A', 500000);

INSERT INTO SYSTEM.DEPARTAMENTOS (DEPARTAMENTO_ID, NOMBRE_DEPARTAMENTO, UBICACION, PRESUPUESTO)
VALUES (SYSTEM.SEQ_DEPARTAMENTOS.NEXTVAL, 'Recursos Humanos', 'Edificio B', 200000);

INSERT INTO SYSTEM.EMPLEADOS (EMPLEADO_ID, NOMBRE, APELLIDO, EMAIL, SALARIO, DEPARTAMENTO_ID)
VALUES (SYSTEM.SEQ_EMPLEADOS.NEXTVAL, 'Juan', 'Pérez', 'juan.perez@empresa.com', 3500.00, 1);

INSERT INTO SYSTEM.EMPLEADOS (EMPLEADO_ID, NOMBRE, APELLIDO, EMAIL, SALARIO, DEPARTAMENTO_ID)
VALUES (SYSTEM.SEQ_EMPLEADOS.NEXTVAL, 'María', 'González', 'maria.gonzalez@empresa.com', 4200.00, 1);

INSERT INTO SYSTEM.EMPLEADOS (EMPLEADO_ID, NOMBRE, APELLIDO, EMAIL, SALARIO, DEPARTAMENTO_ID)
VALUES (SYSTEM.SEQ_EMPLEADOS.NEXTVAL, 'Carlos', 'Rodríguez', 'carlos.rodriguez@empresa.com', 3000.00, 2);

COMMIT;

-- Ver todas las PDBs disponibles
--SELECT name, open_mode FROM v$pdbs;

-- Ver si las tablas existen en algún esquema
--SELECT owner, table_name FROM dba_tables 
--WHERE table_name IN ('EMPLEADOS', 'DEPARTAMENTOS');



--SELECT * FROM SYS.EMPLEADOS;
--SELECT * FROM SYS.DEPARTAMENTOS;
