-- Script para crear tablas en Oracle XE 18 usando el esquema SYSTEM
-- NO usar ALTER SESSION SET CONTAINER, las tablas se crean en TESTDB automáticamente

-- 1. Crear tabla de departamentos
CREATE TABLE SYSTEM.DEPARTAMENTOS (
    DEPARTAMENTO_ID NUMBER(10) PRIMARY KEY,
    NOMBRE_DEPARTAMENTO VARCHAR2(100) NOT NULL,
    UBICACION VARCHAR2(200),
    PRESUPUESTO NUMBER(12,2),
    FECHA_CREACION DATE DEFAULT SYSDATE
);

-- 2. Crear tabla de empleados
CREATE TABLE SYSTEM.EMPLEADOS (
    EMPLEADO_ID NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    FECHA_CONTRATACION DATE DEFAULT SYSDATE,
    SALARIO NUMBER(10,2) CHECK (SALARIO > 0),
    DEPARTAMENTO_ID NUMBER(10),
    ACTIVO CHAR(1) DEFAULT 'S' CHECK (ACTIVO IN ('S', 'N'))
);

-- 3. Agregar foreign key
ALTER TABLE SYSTEM.EMPLEADOS 
ADD CONSTRAINT FK_EMPLEADO_DEPARTAMENTO 
FOREIGN KEY (DEPARTAMENTO_ID) 
REFERENCES SYSTEM.DEPARTAMENTOS(DEPARTAMENTO_ID);

-- 4. Crear secuencias
CREATE SEQUENCE SYSTEM.SEQ_DEPARTAMENTOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SYSTEM.SEQ_EMPLEADOS START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 5. Datos de prueba
INSERT INTO SYSTEM.DEPARTAMENTOS (DEPARTAMENTO_ID, NOMBRE_DEPARTAMENTO, UBICACION, PRESUPUESTO)
VALUES (SYSTEM.SEQ_DEPARTAMENTOS.NEXTVAL, 'Tecnología', 'Edificio A', 500000);

INSERT INTO SYSTEM.DEPARTAMENTOS (DEPARTAMENTO_ID, NOMBRE_DEPARTAMENTO, UBICACION, PRESUPUESTO)
VALUES (SYSTEM.SEQ_DEPARTAMENTOS.NEXTVAL, 'Recursos Humanos', 'Edificio B', 200000);

INSERT INTO SYSTEM.EMPLEADOS (EMPLEADO_ID, NOMBRE, APELLIDO, EMAIL, SALARIO, DEPARTAMENTO_ID)
VALUES (SYSTEM.SEQ_EMPLEADOS.NEXTVAL, 'Juan', 'Pérez', 'juan.perez@empresa.com', 3500.00, 1);

INSERT INTO SYSTEM.EMPLEADOS (EMPLEADO_ID, NOMBRE, APELLIDO, EMAIL, SALARIO, DEPARTAMENTO_ID)
VALUES (SYSTEM.SEQ_EMPLEADOS.NEXTVAL, 'María', 'González', 'maria.gonzalez@empresa.com', 4200.00, 1);

INSERT INTO SYSTEM.EMPLEADOS (EMPLEADO_ID, NOMBRE, APELLIDO, EMAIL, SALARIO, DEPARTAMENTO_ID)
VALUES (SYSTEM.SEQ_EMPLEADOS.NEXTVAL, 'Carlos', 'Rodríguez', 'carlos.rodriguez@empresa.com', 3000.00, 2);



CREATE TABLE SYSTEM.ACINS (
	INS_CRA_COD NUMBER(3,0),
	INS_EST_COD NUMBER(11,0),
	INS_ASI_COD NUMBER(8,0),
	INS_GR NUMBER(10,0),
	INS_NOTA NUMBER(2,0),
	INS_OBS NUMBER(2,0),
	INS_SECUENCIA NUMBER(4,0),
	INS_ESTADO VARCHAR2(1) DEFAULT 'A',
	INS_ANO NUMBER(4,0),
	INS_PER NUMBER(1,0),
	INS_NOTA_PAR1 NUMBER(2,0),
	INS_NOTA_PAR2 NUMBER(2,0),
	INS_NOTA_PAR3 NUMBER(2,0),
	INS_NOTA_PAR4 NUMBER(2,0),
	INS_NOTA_PAR5 NUMBER(2,0),
	INS_NOTA_LAB NUMBER(2,0),
	INS_NOTA_EXA NUMBER(2,0),
	INS_NOTA_HAB NUMBER(2,0),
	INS_NOTA_ACU NUMBER(4,2),
	INS_USUARIO VARCHAR2(20),
	INS_CRED NUMBER(3,0),
	INS_NRO_HT NUMBER(3,0),
	INS_NRO_HP NUMBER,
	INS_NRO_AUT NUMBER,
	INS_CEA_COD NUMBER(2,0),
	INS_NOTA_PAR6 NUMBER,
	INS_TOT_FALLAS NUMBER(2,0) DEFAULT 0 ,
	INS_SEM NUMBER(2,0) DEFAULT 0,
	INS_HOR_ALTERNATIVO NUMBER(3,0) DEFAULT 0 ,
	CONSTRAINT PK_ACINS PRIMARY KEY (INS_ANO,INS_PER,INS_EST_COD,INS_ASI_COD),
	CONSTRAINT SYS_C0018136 CHECK ("INS_ANO" IS NOT NULL),
	CONSTRAINT SYS_C0018137 CHECK ("INS_PER" IS NOT NULL),
	CONSTRAINT SYS_C0018138 CHECK ("INS_TOT_FALLAS" IS NOT NULL),
	CONSTRAINT SYS_C0018139 CHECK ("INS_HOR_ALTERNATIVO" IS NOT NULL),
	CONSTRAINT XNN_ACINS_ASI_COD CHECK ("INS_ASI_COD" IS NOT NULL),
	CONSTRAINT XNN_ACINS_CRA_COD CHECK ("INS_CRA_COD" IS NOT NULL),
	CONSTRAINT XNN_ACINS_EST_COD CHECK ("INS_EST_COD" IS NOT NULL),
	CONSTRAINT XNN_ACINS_GR CHECK ("INS_GR" IS NOT NULL)
	--CONSTRAINT FK_ACINS_ACASI_CUR FOREIGN KEY (INS_ANO,INS_PER,INS_ASI_COD,INS_GR) REFERENCES MNTAC.ACCURSO(CUR_APE_ANO,CUR_APE_PER,CUR_ASI_COD,CUR_NRO),
	--CONSTRAINT FK_ACINS_CRA_COD1 FOREIGN KEY (INS_CRA_COD) REFERENCES MNTAC.ACCRA(CRA_COD),
	--CONSTRAINT FK_ACINS_EST_COD1 FOREIGN KEY (INS_EST_COD) REFERENCES MNTAC.ACEST(EST_COD)
);
CREATE INDEX IND_ACINS_ADICIONES ON SYSTEM.ACINS (INS_ASI_COD,INS_CEA_COD,INS_GR,INS_EST_COD,INS_ANO,INS_PER,INS_ESTADO);
CREATE UNIQUE INDEX IND_ACINS_ANPEASIGREST ON SYSTEM.ACINS (INS_ANO,INS_PER,INS_ASI_COD,INS_GR,INS_EST_COD);
CREATE INDEX IND_ACINS_EST_COD ON SYSTEM.ACINS (INS_EST_COD);
CREATE INDEX IND_ASI_COD ON SYSTEM.ACINS (INS_ASI_COD);
CREATE INDEX IND_INSESTADO ON SYSTEM.ACINS (INS_ESTADO);
--CREATE UNIQUE INDEX PK_ACINS ON SYSTEM.ACINS (INS_ANO,INS_PER,INS_EST_COD,INS_ASI_COD);

CREATE TABLE SYSTEM.ACCURSOS (
	CUR_ID NUMBER(10,0),
	CUR_APE_ANO NUMBER(4,0),
	CUR_APE_PER NUMBER(1,0),
	CUR_ASI_COD NUMBER(8,0),
	CUR_GRUPO NUMBER(5,0),
	CUR_CRA_COD NUMBER(3,0),
	CUR_DEP_COD NUMBER(4,0),
	CUR_NRO_CUPO NUMBER(3,0),
	CUR_NRO_INS NUMBER(3,0),
	CUR_ESTADO VARCHAR2(3),
	CUR_PAR1 NUMBER(3,0),
	CUR_PAR2 NUMBER(3,0),
	CUR_PAR3 NUMBER(3,0),
	CUR_PAR4 NUMBER(3,0),
	CUR_PAR5 NUMBER(3,0),
	CUR_PAR6 NUMBER(3,0),
	CUR_LAB NUMBER(2,0),
	CUR_EXA NUMBER(2,0),
	CUR_HAB NUMBER(2,0),
	CUR_CAP_MAX NUMBER(3,0),
	CUR_HOR_ALTERNATIVO NUMBER(3,0),
	CUR_TIPO NUMBER(3,0),
	CONSTRAINT ACCURSOS_PK PRIMARY KEY (CUR_ID),
	CONSTRAINT SYS_C0018611 CHECK ("CUR_ID" IS NOT NULL),
	CONSTRAINT SYS_C0018612 CHECK ("CUR_APE_ANO" IS NOT NULL),
	CONSTRAINT SYS_C0018613 CHECK ("CUR_APE_PER" IS NOT NULL),
	CONSTRAINT SYS_C0018614 CHECK ("CUR_ASI_COD" IS NOT NULL),
	CONSTRAINT SYS_C0018615 CHECK ("CUR_GRUPO" IS NOT NULL),
	CONSTRAINT SYS_C0018616 CHECK ("CUR_CRA_COD" IS NOT NULL),
	CONSTRAINT SYS_C0018617 CHECK ("CUR_DEP_COD" IS NOT NULL),
	CONSTRAINT SYS_C0018618 CHECK ("CUR_NRO_CUPO" IS NOT NULL)
	--CONSTRAINT ACCURSOS_ACTIPOCURSO_FK1 FOREIGN KEY (CUR_TIPO) REFERENCES MNTAC.ACTIPOCURSO(TIP_CUR_COD)
);
CREATE INDEX ACCURSOS_ANO_PER ON SYSTEM.ACCURSOS (CUR_ID,CUR_APE_ANO,CUR_APE_PER);
--CREATE UNIQUE INDEX ACCURSOS_PK ON SYSTEM.ACCURSOS (CUR_ID);
CREATE INDEX IND_ACCURSOS_ADICIONES ON SYSTEM.ACCURSOS (CUR_ID,CUR_ASI_COD);
CREATE INDEX IND_ACCURSOS_ADICIONES2 ON SYSTEM.ACCURSOS (CUR_APE_ANO,CUR_APE_PER,CUR_ID);
CREATE INDEX IND_ACCURSOS_ADICIONES3 ON SYSTEM.ACCURSOS (CUR_ASI_COD,CUR_APE_ANO,CUR_APE_PER,CUR_ID);

INSERT INTO SYSTEM.ACINS
(INS_CRA_COD, INS_EST_COD, INS_ASI_COD, INS_GR, INS_NOTA, INS_OBS, INS_SECUENCIA, INS_ESTADO, INS_ANO, INS_PER, INS_NOTA_PAR1, INS_NOTA_PAR2, INS_NOTA_PAR3, INS_NOTA_PAR4, INS_NOTA_PAR5, INS_NOTA_LAB, INS_NOTA_EXA, INS_NOTA_HAB, INS_NOTA_ACU, INS_USUARIO, INS_CRED, INS_NRO_HT, INS_NRO_HP, INS_NRO_AUT, INS_CEA_COD, INS_NOTA_PAR6, INS_TOT_FALLAS, INS_SEM, INS_HOR_ALTERNATIVO)
VALUES(785, 20252785008, 2403, 181560, 46, 0, NULL, 'A', 2025, 3, 50, 44, NULL, 46, 50, NULL, 46, NULL, 46.28, '33992548', 2, 2, 2, 2, 1, 45, 0, 0, 0);
INSERT INTO SYSTEM.ACINS
(INS_CRA_COD, INS_EST_COD, INS_ASI_COD, INS_GR, INS_NOTA, INS_OBS, INS_SECUENCIA, INS_ESTADO, INS_ANO, INS_PER, INS_NOTA_PAR1, INS_NOTA_PAR2, INS_NOTA_PAR3, INS_NOTA_PAR4, INS_NOTA_PAR5, INS_NOTA_LAB, INS_NOTA_EXA, INS_NOTA_HAB, INS_NOTA_ACU, INS_USUARIO, INS_CRED, INS_NRO_HT, INS_NRO_HP, INS_NRO_AUT, INS_CEA_COD, INS_NOTA_PAR6, INS_TOT_FALLAS, INS_SEM, INS_HOR_ALTERNATIVO)
VALUES(785, 20252785007, 2403, 181560, 45, 0, NULL, 'A', 2025, 3, 50, 33, NULL, 50, 50, NULL, 47, NULL, 45.3, '33992548', 2, 2, 2, 2, 1, 48, 0, 0, 0);
INSERT INTO SYSTEM.ACINS
(INS_CRA_COD, INS_EST_COD, INS_ASI_COD, INS_GR, INS_NOTA, INS_OBS, INS_SECUENCIA, INS_ESTADO, INS_ANO, INS_PER, INS_NOTA_PAR1, INS_NOTA_PAR2, INS_NOTA_PAR3, INS_NOTA_PAR4, INS_NOTA_PAR5, INS_NOTA_LAB, INS_NOTA_EXA, INS_NOTA_HAB, INS_NOTA_ACU, INS_USUARIO, INS_CRED, INS_NRO_HT, INS_NRO_HP, INS_NRO_AUT, INS_CEA_COD, INS_NOTA_PAR6, INS_TOT_FALLAS, INS_SEM, INS_HOR_ALTERNATIVO)
VALUES(785, 20252785007, 2458, 181623, 41, 0, NULL, 'A', 2025, 3, 35, 45, 41, 35, 44, NULL, 44, NULL, 40.9, '52458225', 3, 2, 2, 5, 3, 42, 1, 0, 0);
INSERT INTO SYSTEM.ACINS
(INS_CRA_COD, INS_EST_COD, INS_ASI_COD, INS_GR, INS_NOTA, INS_OBS, INS_SECUENCIA, INS_ESTADO, INS_ANO, INS_PER, INS_NOTA_PAR1, INS_NOTA_PAR2, INS_NOTA_PAR3, INS_NOTA_PAR4, INS_NOTA_PAR5, INS_NOTA_LAB, INS_NOTA_EXA, INS_NOTA_HAB, INS_NOTA_ACU, INS_USUARIO, INS_CRED, INS_NRO_HT, INS_NRO_HP, INS_NRO_AUT, INS_CEA_COD, INS_NOTA_PAR6, INS_TOT_FALLAS, INS_SEM, INS_HOR_ALTERNATIVO)
VALUES(785, 20252785007, 2407, 181565, 41, 0, NULL, 'A', 2025, 3, 35, 35, 35, 44, 44, NULL, 46, NULL, 41.45, '80933093', 3, 2, 2, 5, 1, 44, 0, 0, 0);
INSERT INTO SYSTEM.ACINS
(INS_CRA_COD, INS_EST_COD, INS_ASI_COD, INS_GR, INS_NOTA, INS_OBS, INS_SECUENCIA, INS_ESTADO, INS_ANO, INS_PER, INS_NOTA_PAR1, INS_NOTA_PAR2, INS_NOTA_PAR3, INS_NOTA_PAR4, INS_NOTA_PAR5, INS_NOTA_LAB, INS_NOTA_EXA, INS_NOTA_HAB, INS_NOTA_ACU, INS_USUARIO, INS_CRED, INS_NRO_HT, INS_NRO_HP, INS_NRO_AUT, INS_CEA_COD, INS_NOTA_PAR6, INS_TOT_FALLAS, INS_SEM, INS_HOR_ALTERNATIVO)
VALUES(785, 20252785007, 2426, 181591, 38, 0, NULL, 'A', 2025, 3, 35, 34, NULL, NULL, NULL, NULL, 45, NULL, 37.65, '66922387', 3, 2, 2, 5, 1, NULL, 0, 0, 0);


INSERT INTO SYSTEM.ACCURSOS
(CUR_ID, CUR_APE_ANO, CUR_APE_PER, CUR_ASI_COD, CUR_GRUPO, CUR_CRA_COD, CUR_DEP_COD, CUR_NRO_CUPO, CUR_NRO_INS, CUR_ESTADO, CUR_PAR1, CUR_PAR2, CUR_PAR3, CUR_PAR4, CUR_PAR5, CUR_PAR6, CUR_LAB, CUR_EXA, CUR_HAB, CUR_CAP_MAX, CUR_HOR_ALTERNATIVO, CUR_TIPO)
VALUES(173772, 2025, 1, 11015, 202, 379, 32, 30, 31, 'A', 35, NULL, NULL, 15, 20, NULL, NULL, 30, 70, 39, 0, 1);
INSERT INTO SYSTEM.ACCURSOS
(CUR_ID, CUR_APE_ANO, CUR_APE_PER, CUR_ASI_COD, CUR_GRUPO, CUR_CRA_COD, CUR_DEP_COD, CUR_NRO_CUPO, CUR_NRO_INS, CUR_ESTADO, CUR_PAR1, CUR_PAR2, CUR_PAR3, CUR_PAR4, CUR_PAR5, CUR_PAR6, CUR_LAB, CUR_EXA, CUR_HAB, CUR_CAP_MAX, CUR_HOR_ALTERNATIVO, CUR_TIPO)
VALUES(173773, 2025, 1, 11016, 202, 379, 32, 22, 21, 'A', 5, 10, 20, 10, 10, 15, NULL, 30, 70, 35, 0, 1);
INSERT INTO SYSTEM.ACCURSOS
(CUR_ID, CUR_APE_ANO, CUR_APE_PER, CUR_ASI_COD, CUR_GRUPO, CUR_CRA_COD, CUR_DEP_COD, CUR_NRO_CUPO, CUR_NRO_INS, CUR_ESTADO, CUR_PAR1, CUR_PAR2, CUR_PAR3, CUR_PAR4, CUR_PAR5, CUR_PAR6, CUR_LAB, CUR_EXA, CUR_HAB, CUR_CAP_MAX, CUR_HOR_ALTERNATIVO, CUR_TIPO)
VALUES(173774, 2025, 1, 11016, 203, 379, 32, 23, 24, 'A', 5, 10, 20, 10, 10, 15, NULL, 30, 70, 30, 0, 1);
INSERT INTO SYSTEM.ACCURSOS
(CUR_ID, CUR_APE_ANO, CUR_APE_PER, CUR_ASI_COD, CUR_GRUPO, CUR_CRA_COD, CUR_DEP_COD, CUR_NRO_CUPO, CUR_NRO_INS, CUR_ESTADO, CUR_PAR1, CUR_PAR2, CUR_PAR3, CUR_PAR4, CUR_PAR5, CUR_PAR6, CUR_LAB, CUR_EXA, CUR_HAB, CUR_CAP_MAX, CUR_HOR_ALTERNATIVO, CUR_TIPO)
VALUES(173775, 2025, 1, 11016, 204, 379, 32, 25, 23, 'A', 15, 20, NULL, 15, 20, NULL, NULL, 30, 70, 30, 0, 3);
INSERT INTO SYSTEM.ACCURSOS
(CUR_ID, CUR_APE_ANO, CUR_APE_PER, CUR_ASI_COD, CUR_GRUPO, CUR_CRA_COD, CUR_DEP_COD, CUR_NRO_CUPO, CUR_NRO_INS, CUR_ESTADO, CUR_PAR1, CUR_PAR2, CUR_PAR3, CUR_PAR4, CUR_PAR5, CUR_PAR6, CUR_LAB, CUR_EXA, CUR_HAB, CUR_CAP_MAX, CUR_HOR_ALTERNATIVO, CUR_TIPO)
VALUES(173779, 2025, 1, 17901, 203, 379, 32, 30, 29, 'A', 5, 10, 20, 8, 7, 20, 0, 30, 70, 30, 0, 1);



COMMIT;



-- Ver todas las PDBs disponibles
--SELECT name, open_mode FROM v$pdbs;

-- Ver si las tablas existen en algún esquema
--SELECT owner, table_name FROM dba_tables 
--WHERE table_name IN ('EMPLEADOS', 'DEPARTAMENTOS');



--SELECT * FROM SYS.EMPLEADOS;
--SELECT * FROM SYS.DEPARTAMENTOS;

--Host: oracle-db
--Port: 1521
--Connection type: SID (no Service)
--Database/SID: XE ← (no TESTDB)
--User: system
--Password: OraclePass123